### ISSUE TITLE
CEC issues with Jarvis

### ISSUE THREAD

**Issue by jasonrubli** [joshjowen/script.json-cec#3] opened 2016-02-27 23:30 UTC
Since upgrading to Kodi 16 (Jarvis), I've been unable to pass commands. Both standby and activate look like they are accepted, but my TV is no longer affected.

This may be a difference in how Jarvis handles CEC as my cronjobs using cron-XBMC to pass CECStandby and CECActivateSource are not functioning either.

I'm running OSMC on a Raspberry Pi 2. The TV is turned off and on when kodi is shutdown and restarted, so the functionality remains.

Is this just me or are others seeing similar results?
Thanks!

**Comment by kwijibo007** [comment] 2016-03-21 01:53
Same problem since upgrading to Kodi 16 (Jarvis). Commands are accepted from the plugin but nothing happens on the TV.

**Comment by joshjowen** [comment] 2016-03-29 05:41
I've only just upgraded to Jarvis now and it appears to be an issue with KODI, maybe they have changed something with the CEC built in commands. It isn't working with the application kodi-send either so unfortunately I haven't been able to find a solution.

**Comment by mymaill11** [comment] 2016-07-13 08:31
Were you able to find a solution? Is Krypton going to address the issue with the CEC builtin commands?

**Comment by jonathanbower** [comment] 2016-08-08 07:40
I think it is fixed in Krypton with this PR, https://github.com/xbmc/xbmc/pull/9535

I've not verified it though.

**Comment by corro** [comment] 2017-02-10 17:26
I can confirm that this issue has been fixed with the release of Krypton.

**Comment by seh-len** [comment] 2017-03-03 05:57
@corro, does CECStandby work for you?
It works using cec-client but this disconnects the cec connection of kodi.

Edit:
Found this: http://forum.kodi.tv/showthread.php?tid=265743&pid=2291592#pid2291592
After enabling 'devices to power off' in kodi cec settings, it is working as expected.

**Closed as completed** 2017-03-09 07:35 UTC
